name: python-project-lvl2
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install poetry
      - run: pip install flake8
      - run: poetry add --dev flake8
      - run: make lint

